### PR TITLE
Fixed issues

### PR DESCRIPTION
**Pull request by below**
Fixed your code, and your test. Please review

Test also works now!

### CODE REVIEW

**Comment by stuffmc** [comment]
I understand the fix, but does that change anything in the execution? I still see the same `Espresso` error when running your version. The code doesn't even reach the `guard let document`, as it fails in the first `catch`.

**Comment by below** [comment]
What are you running it on? I am running it on an iPhone 12 Simulator (iOS 15):
```
Test Suite 'All tests' started at 2021-06-22 09:36:51.249
Test Suite 'ImageOCRTests.xctest' started at 2021-06-22 09:36:51.251
Test Suite 'ImageOCRTests' started at 2021-06-22 09:36:51.252
Test Case '-[ImageOCRTests.ImageOCRTests testExample]' started.
Power Adapter
85W MagSafe 2
Test Case '-[ImageOCRTests.ImageOCRTests testExample]' passed (7.379 seconds).
Test Suite 'ImageOCRTests' passed at 2021-06-22 09:36:58.631.
	 Executed 1 test, with 0 failures (0 unexpected) in 7.379 (7.380) seconds
Test Suite 'ImageOCRTests.xctest' passed at 2021-06-22 09:36:58.632.
	 Executed 1 test, with 0 failures (0 unexpected) in 7.379 (7.381) seconds
Test Suite 'All tests' passed at 2021-06-22 09:36:58.633.
	 Executed 1 test, with 0 failures (0 unexpected) in 7.379 (7.383) seconds
Program ended with exit code: 0
```

**Comment by stuffmc** [comment]
Crazy. An iPad Simulator (iOS 15) or iPhone 12 Pro Max Simulator (iOS 15). Are you running this in Monterey?! I'm running it on Big Sur, but that shouldn't make a difference. We definitely do need to do a Screenshare about that. It sounds as if I'd be doing something terribly wrong :(

**Comment by below** [comment]
Big Sur here. Screenshare later?

**Comment by below** [comment]
Just so that we are on the same page: I can start the tests successfully from the  command line like this:

`xcrun xcodebuild test -sdk=iOSSimulator -destination 'name=iPhone 12' -scheme 'ImageOCR'`

**Comment by stuffmc** [comment]
I press ⌘ U in Xcode.

**Comment by below** [comment]
That also produces successful tests on this machine, macOS Big Sur 11.4 (20F71), Xcode Version 13.0 beta (13A5154h)

**Comment by chiahao** [comment]
I got the same test error, Monterey 12.0 Beta(21A5294g), Xcode Version 13.0 beta 4 (13A5201i), still don't know why.

```
Testing started
Test Suite 'All tests' started at 2021-08-07 01:14:56.243
Test Suite 'ImageOCRTests.xctest' started at 2021-08-07 01:14:56.244
Test Suite 'ImageOCRTests' started at 2021-08-07 01:14:56.246
Test Case '-[ImageOCRTests.ImageOCRTests testExample]' started.
2021-08-07 01:14:57.339709+0800 xctest[1873:42013] ImageAnalyzer error -37:Espresso error in void vision::mod::ImageAnalyzer::initNetwork(const char *, const char *) @ /Library/Caches/com.apple.xbs/Sources/Vision_Sim/Vision-5.0.41.1/Libraries/cvml-Core/ImageAnalyzer/ImageAnalyzer.cpp:62
Error Domain=com.apple.vis Code=9 "failed to create image analyzer" UserInfo={NSLocalizedDescription=failed to create image analyzer, NSUnderlyingError=0x600002b85620 {Error Domain=com.apple.vis Code=9 "ImageAnalyzer failure with status 8539 (Espresso error)" UserInfo={NSLocalizedDescription=ImageAnalyzer failure with status 8539 (Espresso error)}}}
/Users/chiahao/Downloads/ImageOCR-main/Tests/ImageOCRTests/ImageOCRTests.swift:15: error: -[ImageOCRTests.ImageOCRTests testExample] : XCTAssertEqual failed: ("nil") is not equal to ("Optional("85W MagSafe 2/nPower Adapter")")
Test Case '-[ImageOCRTests.ImageOCRTests testExample]' failed (1.390 seconds).
Test Suite 'ImageOCRTests' failed at 2021-08-07 01:14:57.637.
	 Executed 1 test, with 1 failure (0 unexpected) in 1.390 (1.391) seconds
Test Suite 'ImageOCRTests.xctest' failed at 2021-08-07 01:14:57.637.
	 Executed 1 test, with 1 failure (0 unexpected) in 1.390 (1.394) seconds
Test Suite 'All tests' failed at 2021-08-07 01:14:57.637.
	 Executed 1 test, with 1 failure (0 unexpected) in 1.390 (1.395) seconds
2021-08-07 01:15:18.371 xcodebuild[1684:39927] [MT] IDETestOperationsObserverDebug: 43.868 elapsed -- Testing started completed.
2021-08-07 01:15:18.382 xcodebuild[1684:39927] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2021-08-07 01:15:18.382 xcodebuild[1684:39927] [MT] IDETestOperationsObserverDebug: 43.869 sec, +43.869 sec -- end
```

**Comment by ericagredo** [comment]
Did you ever figure it out? I get same errors and dont see anything online

**Comment by below** [comment]
> Did you ever figure it out? I get same errors and dont see anything online

What are you trying it on? I have no issues

**Comment by ericagredo** [comment]
> > Did you ever figure it out? I get same errors and dont see anything online
> 
> What are you trying it on? I have no issues

I got it to work but only on my physical phone. Doesn’t work on simulator XCode 13 RC for me.

**Comment by below** [comment]
> I got it to work but only on my physical phone. Doesn’t work on simulator XCode 13 RC for me.

Simulator, iPhone 12, Xcode 13.0 (13A233), macOS BS 11.5.2 (20G95),  Intel Core i7

How does your setup differ?

**Comment by ericagredo** [comment]
> > I got it to work but only on my physical phone. Doesn’t work on simulator XCode 13 RC for me.
> 
> Simulator, iPhone 12, Xcode 13.0 (13A233), macOS BS 11.5.2 (20G95), Intel Core i7
> 
> How does your setup differ?

Simulator: iPhone 12 Pro, Xcode 13.0 (13A233), macOS BS 11.5.2, M1

**Comment by below** [comment]
"File a Radar":

This works perfectly well on my Intel Mac, but on a Mac mini (M1, 2020) I am getting the same issue as all of you. It appears to be an ARM issue.

```
Error Domain=com.apple.vis Code=9 "failed to create image analyzer" UserInfo={NSLocalizedDescription=failed to create image analyzer, NSUnderlyingError=0x6000027af1e0 {Error Domain=com.apple.vis Code=9 "ImageAnalyzer failure with status 8539 (Espresso error)" UserInfo={NSLocalizedDescription=ImageAnalyzer failure with status 8539 (Espresso error)}}}
```

**Review by stuffmc — APPROVED** [review]
'APPROVE' performed by Xcode.

**Pull request merged**
